### PR TITLE
MyReadingManga fix bug "Not found"

### LINKED ISSUE #5675: MyReadingManga unable to load in webview
### Source information

MyReadingManga 1.4.53

### Source language

English

### Steps to reproduce

1. Open webview from MyReadingManga extension
2. Error show "NOT FOUND"

### Expected behavior

Be able to properly load the website after manual cloudflare verify like in the typical browser.

### Actual behavior

Error show "NOT FOUND" on loading in webview

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13 MIUI 14.0.8

### Other details

This site is known for only able to do a manual cloudflare **ONLY**.
Since the webview is broken lead to unable to do cloudflare verify lead to extension broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Hayanek**
Checklist:
Closes #5675 

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
remove the header in interceptor as well, [example](https://github.com/keiyoushi/extensions-source/blob/1fc164d5acc54916ed04a6f16dbbf91dc6c7bc3e/src/id/mgkomik/src/eu/kanade/tachiyomi/extension/id/mgkomik/MGKomik.kt#L38)

**Comment by kkurootetsuro** [comment]
hello does this also addresses https://github.com/keiyoushi/extensions-source/issues/3563 ?

**Comment by Hayanek** [comment]
> hello does this also addresses #3563 ?

nope only error that it was not possible to enter viewmode to accept cloudflare

**Comment by kkurootetsuro** [comment]
> > hello does this also addresses #3563 ?
> 
> nope only error that it was not possible to enter viewmode to accept cloudflare

oh okay... thank you

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
