### PR TITLE
Remove One Piece Ex

### LINKED ISSUE #131: One Piece Ex - ID1ID2
### Source information

One Piece Ex 1.4.6

### Source language

Portuguese (Brazil)

### Steps to reproduce

1. Open the source.

### Expected behavior

Show the content, the website works in WebView.

### Actual behavior

Error "ID1ID2: actual 0x00001fef != expected
0x00001f8b".
Screenshot_20240110_222020_Tachiyomi

### Tachiyomi version

0.15.1-6404

### Android version

Android 14

### Other details

[tachiyomi_crash_logs.txt](https://github.com/keiyoushi/extensions-source/files/13896049/tachiyomi_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beer-psi**
Extension is broken, and it doesn't seem like you can read manga on there anymore.

Closes #131 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by DFBR1208** [comment]
One Piece ex is THE brazilian scanslator for one piece, I don't know anything about how the extension work, but in Kotatsu is working, so please don't remove it, if it's completely broken then I guess that's nothing to do, Kotatsu uses this URL: https://onepieceex.net/mangas/leitor/ is slightly different from the extension (https://onepieceex.net/mangas/?type=main)

**Comment by beer-psi** [comment]
If it works for Kotatsu then I guess I haven't looked hard enough. Admittedly I do not know my way around Portugese. Will turn this PR into a normal update.

**Comment by beer-psi** [comment]
Seems like I'm region blocked because I can't see the elements that Kotatsu is scraping. Oh well, pt-BR speakers please step up.

**Comment by DFBR1208** [comment]
Screenshot_20240111_014309_Kotatsu

Screenshot_20240111_014315_Kotatsu
  
Well, I really don't know what to say, here I have some prints of it working in kotatsu, I don't have a cruel about being regional blocked

**Pull request closed without merging**
