### PR TITLE
GenzToons(Surya Scans): Update domain, icons and extension name

### LINKED ISSUE #3858: surya moving
### Source information

Surya Scans

### Source language

English

### Source new URL

http://genztoons.com

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3858

The manga paths are compatible

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
current site is working for me...?

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by Edwardboy16** [comment]
I don't know if I am the only one. But surya Scans is no longer available for me. I can't find it at all in the extensions list.

**Comment by Smol-Ame** [comment]
> I don't know if I am the only one. But surya Scans is no longer available for me. I can't find it at all in the extensions list.

As mentioned in the title, Surya Scans extension was renamed to Genz Toons, (edit) it should appear as Genz Toons currently

**Comment by Edwardboy16** [comment]
> > I don't know if I am the only one. But surya Scans is no longer available for me. I can't find it at all in the extensions list.
> 
> As mentioned in the title, Surya Scans extension was renamed to Genz Toons, (edit) it should appear as Genz Toons currently

> > I don't know if I am the only one. But surya Scans is no longer available for me. I can't find it at all in the extensions list.
> 
> As mentioned in the title, Surya Scans extension was renamed to Genz Toons, (edit) it should appear as Genz Toons currently

I did not notice that. Thanks for pointing it out.

**Pull request merged**
