### PR TITLE
Rackus(PMScans): Migrate theme and rebranding

### LINKED ISSUE #5005: PMScans - no result found
### Source information

PMScans 1.4.36

### Source language

English

### Steps to reproduce

1. View latest / popular / search resulted in no result found
2. Open webview open in rackusreads.com & resulted fine.
3. The manga title shown in project update

### Expected behavior

Can view manga & download chapter

### Actual behavior

Cannot view manga

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #5005

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by choppeh** [comment]
Rebranding can be applied after theme migration.

**Comment by AwkwardPeak7** [comment]
> Rebranding can be applied after theme migration.

any reason why not in the same pr?

**Comment by choppeh** [comment]
> any reason why not in the same pr?

I thought it might be confusing for users if there is a rebranding along with the theme migrate, perhaps they think the extension has been deleted

**Comment by AwkwardPeak7** [comment]
> I thought it might be confusing for users if there is a rebranding along with the theme migraine, perhaps they think the extension has been deleted

many would think that regardless...

**Comment by Riztard** [comment]
some of the reason why we should just remove/migrate the ext and kept the id when source rebranding/name change is quite drastic.
folder name and content didnt quite match as well. make sense for short term but not for long

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
