### PR TITLE
Manga Demon: update domain

### LINKED ISSUE #3778: Manga Demon URL change
### Source information

Manga Demon 1.4.11

### Source language

English

### Source new URL

https://mgdemon.org/

### Other details

The previous URL was https://comicdemons.com. The titles and thumbnails are loading in the app, but when clicking/tapping it, it says "No chapters found".

image
image

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #3778

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by aeron-leeding** [comment]
whats the timeline on the review?

**Comment by Smol-Ame** [comment]
> whats the timeline on the review?

Whenever the extension maintainers have time to check the code & approve the request. Be patient

**Comment by aeron-leeding** [comment]
> > whats the timeline on the review?
> 
> Whenever the extension maintainers have time to check the code & approve the request. Be patient

Just asking the typical timeline for these updates? So I know if I should add new or migrate sources?

**Comment by Smol-Ame** [comment]
> Just asking the typical timeline for these updates? So I know if I should add new or migrate sources?

Let's say from a day to a week

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
