### PR TITLE
Add condition to only run codeberg_mirror on keiyoushi repo...

### PR DESCRIPTION
**Pull request by cuong-tran**
… instead of other forks

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by stevenyomi** [comment]
Could you apply the condition to the entire workflow instead of the individual steps?

**Comment by beer-psi** [comment]
> Could you apply the condition to the entire workflow instead of the individual steps?

I think you can't apply it at workflow-level, only job-level.

**Comment by stevenyomi** [comment]
Then apply it on the job? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

**Comment by beer-psi** [comment]
> Then apply it on the job? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

That's what I suggested in the review.

**Review by stevenyomi — APPROVED** [review]

**Pull request merged**
