### PR TITLE
Manga Demon: Update domain

### PR DESCRIPTION
**Pull request by kn1ghtblood**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by vetleledaal** [comment]
#2546 can be closed by this PR, you must add it to your post in the specified format.

Did you verify these changes through Android Studio?
Apologies for the caution, but first-time contributions made through GitHub's web interface have historically been untested. A screenshot of the extension working through Android Studio is sufficient.

**Comment by kn1ghtblood** [comment]
> #2546 can be closed by this PR, you must add it to your post in the specified format.
> 
> Did you verify these changes through Android Studio? Apologies for the caution, but first-time contributions made through GitHub's web interface have historically been untested. A screenshot of the extension working through Android Studio is sufficient.

I don't use Android Studio; actually, I build the extension myself. I just change the domain in the code and build the app through CLI. I understand your concern, and you can close the PR if you want.

**Comment by AwkwardPeak7** [comment]
> I don't use Android Studio; actually, I build the extension myself. I just change the domain in the code and build the app through CLI. I understand your concern, and you can close the PR if you want.

please show screenshot of your build process, thanks

**Comment by kn1ghtblood** [comment]
> > I don't use Android Studio; actually, I build the extension myself. I just change the domain in the code and build the app through CLI. I understand your concern, and you can close the PR if you want.
> 
> please show screenshot of your build process, thanks

image
here is your screenshot. I only changed two files as you can see in the commit i don't understand why you need all this.

**Comment by AwkwardPeak7** [comment]
thank you for your cooperation, the reason is that there are too many people who open untested and broken prs

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
