### PR TITLE
Update Url MangaBat

### LINKED ISSUE #1985: mangabat change
### Source information

mangabat 1.4.9

### Source language

English 

### Source new URL

h.managbat.com

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by GGaro**
Closes: https://github.com/keiyoushi/extensions-source/issues/1985
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by nomaxsnx** [comment]
Please don't keep deleting the pr, as I said, you did almost everything right, you just need to update overrideVersionCode which is in 4, you have to update to 5

Every time you change the extension, you always have to update the overrideVersionCode.

**Comment by nomaxsnx** [comment]
Add the: "Closes: #1985"

on top of the checklist

**Comment by nomaxsnx** [comment]
Please mark an X in (Referenced all related issues in the PR Body)

**Comment by nomaxsnx** [comment]
Change the title to: "Update Url MangaBat".

**Comment by GGaro** [comment]
> Please don't keep deleting the pr, as I said, you did almost everything right, you just need to update overrideVersionCode which is in 4, you have to update to 5
> 
> Every time you change the extension, you always have to update the overrideVersionCode.

Sorry I'm kinda new to GitHub so I didn't know a few things, thanks for the patience.

**Comment by nomaxsnx** [comment]
> > Please don't keep deleting the pr, as I said, you did almost everything right, you just need to update overrideVersionCode which is in 4, you have to update to 5
> > Every time you change the extension, you always have to update the overrideVersionCode.
> 
> Sorry I'm kinda new to GitHub so I didn't know a few things, thanks for the patience.

No problem, just update the overrideVersionCode to 5.

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
