### PR TITLE
FlowerManga: Update Url and Build

### LINKED ISSUE #3054: flower manga change url back
### Source information

Flower Manga 1.4.37

### Source language

Português - Brasil / Portuguese - Brazil

### Source new URL

https://flowermanga.com/

### Other details

image
image

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by nomaxsnx**
Closes: #3054 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
the current link works fine for me.
are the two sites related? both have different results for popular mangas and google tag id is different as well

**Comment by nomaxsnx** [comment]
> the current link works fine for me. are the two sites related? both have different results for popular mangas and google tag id is different as well

Well, until I don't know, because the scan doesn't have discord, everyone in the Brazilian community thought that FlowerManga was "F", because of the Federal Police's anti-piracy operation.

**Comment by nomaxsnx** [comment]
It could possibly be a backup of the site, in case one of the two: ".net" and ".com" went down.

**Comment by AwkwardPeak7** [comment]
idk, can make a new extension for this domain

**Pull request closed without merging**
