### PR TITLE
Magicomi fix selectors

### LINKED ISSUE #5432: Magcomi
### Source information

Magcomi 1.4.5

### Source language

Japanese

### Steps to reproduce

After opening it, it says "no results"

### Expected behavior

Screenshot_2024-10-08-13-38-18-301_app mihon
It was supposed to be something like this

### Actual behavior

but "no results"

### Mihon/Tachiyomi version

0.16.5

### Android version

14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by LefanHu**
Unfinished!!

Closes #5432 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by LefanHu** [comment]
selectors corrected and verified title, cover image url, and manga href are extracted correctly using logcat.... 

just can't seem to figure out why entries seem to be blank when clicking into source.

**Comment by bapeey** [comment]
> just can't seem to figure out why entries seem to be blank when clicking into source.

override `mangaDetailsParse` from multisrc and change selectors too

**Comment by LefanHu** [comment]
To me, it would seem that mangaDetailsParse is working as I can click into an "empty" cover and get a fully detailed manga description...

All the non-blank entries are due to caching after clicking on them

<div>
drawing
drawing
<div>

**Comment by LefanHu** [comment]
just realized this was a duplicate. sorry about that

**Pull request closed without merging**
