### PR TITLE
Split VyvyManga and VyvyManga.org extensions

### LINKED ISSUE #5641: Wrong source URL for Vyvymanga in newest version
### Source information

Vyvymanga 1.4.36

### Source language

English

### Source new URL

vyvymanga.net

### Other details

The newest version of the vyvymanga extension uses the wrong url. Vyvymanga.org is not the official site. Official url is vyvymanga.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #5641
Reverts #5573, .org site is moved to another extension.
Should reopen and unlock #204 (manually)

~~Since the version was bumped and the current version of the VyvyManga extension is broken I have added a comment specifying what version to bump to in a future PR. This ensures both users that did and didn't update the extension will get the new version, when fixed.~~

Preferably this PR would fix the extension, but it did not seem like a quick fix.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
imo should bump it either way, so users don't unnecessarily migrate to the wrong domain version

**Comment by MikeZeDev** [comment]
may fix https://github.com/keiyoushi/extensions-source/issues/5641

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by mentlmelody** [comment]
Coming from #5641, was the decision to have two seperate extensions (one for .org and one for .net)? Or was it decided to keep the .org url? Just trying to understand.

**Comment by AwkwardPeak7** [comment]
two separate extensions

**Pull request merged**
