### PR TITLE
mantrazscan Domain change

### LINKED ISSUE #4759: Mantraz Scan (ES) URL change
### Source information

Mantraz Scan 1.4.38

### Source language

Spanish

### Source new URL

https://artessupremas.com/

### Other details

Mantraz Scan (ES) URL change to https://artessupremas.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #4759

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by vetleledaal** [comment]
Remove trailing slashes from the `baseUrl`. Also, it seems like the old domain is still working?

**Comment by Creepler13** [comment]
> Remove trailing slashes from the `baseUrl`. Also, it seems like the old domain is still working?

True, the other sites always redirected to the new domain so i'm not sure how much of a domain change this is
should i just close it until something actually breaks?

**Comment by AwkwardPeak7** [comment]
it is not redirecting for me... is it based on location?

**Comment by Creepler13** [comment]
Yeah that fact that it is not redirecting is what makes me unsure.The other extensions where i changed the domain always redirected to the new, but this one doesn't. I think iam going to close this PR since even some of the links on the new domain link back to the "old one".

**Pull request closed without merging**
