### PR TITLE
Translate manhuagui

### PR DESCRIPTION
**Pull request by cuong-tran**
Also fix some minor warnings

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [X] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by beer-psi** [comment]
You might want to look into [the i18n library](https://github.com/keiyoushi/extensions-source/blob/main/CONTRIBUTING.md#i18n-library) which can streamline the translation process.

**Comment by stevenyomi** [comment]
Use [`i18n` library](https://github.com/keiyoushi/extensions-source/blob/main/CONTRIBUTING.md#i18n-library).

**Comment by beer-psi** [comment]
Also I can't help but wonder why you're translating a Chinese-only source. Understading the settings and the tags won't help you understand any content.

**Comment by cuong-tran** [comment]
> Also I can't help but wonder why you're translating a Chinese-only source. Understading the settings and the tags won't help you understand any content.

Mostly I want to translate the source with photos only but I can't stand the feeling when trying explore a Chinese source and not understand a thing.

**Comment by beer-psi** [comment]
> not understand a thing.

you still won't understand the most important part (the content) though?

also, why even translate if you don"t understand a thing and has to resort to MTL?

**Comment by beer-psi** [comment]
Closing because you seem to not have a good enough command of the Chinese language and are resorting to machine translation. Feel free to maintain the English versions on your own.

**Pull request closed without merging**
