### PR TITLE
fix "impossible de controuner Cloudflare" Manga Starz

### PR DESCRIPTION
**Pull request by mohamedotaku**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by yemenihandsome** [comment]
> Checklist:
> 
> * [ ]  Updated `extVersionCode` value in `build.gradle` for individual extensions
> * [x]  Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
> * [ ]  Referenced all related issues in the PR body (e.g. "Closes #xyz")
> * [ ]  Added the `isNsfw = true` flag in `build.gradle` when appropriate
> * [x]  Have not changed source names
> * [ ]  Have explicitly kept the `id` if a source's name or language were changed
> * [x]  Have tested the modifications by compiling and running the extension through Android Studio
> * [ ]  Have removed `web_hi_res_512.png` when adding a new extension

and MangaLionz And MangaStarz And Mangalink

**Comment by yemenihandsome** [comment]
@mohamedotaku  and MangaLionz And MangaStarz And Mangalink

**Comment by stevenyomi** [comment]
This chunk of code seems to be from https://github.com/keiyoushi/extensions-source/blob/main/multisrc/overrides/madara/mangalek/src/Mangalek.kt - not sure if this should be pulled up to the Madara class, probably need someone familiar with Madara to review.

**Comment by beer-psi** [comment]
> This chunk of code seems to be from https://github.com/keiyoushi/extensions-source/blob/main/multisrc/overrides/madara/mangalek/src/Mangalek.kt - not sure if this should be pulled up to the Madara class, probably need someone familiar with Madara to review.

Normal Madara search works fine on all of these sites, it's just their normal Madara search endpoint being Cloudflare-protected. Maybe this can be pulled up to the Madara class under an option (e.g. `useFullSearch`) but I don't think we should add more code onto Madara to mitigate a few sites.

**Comment by Riztard** [comment]
> but I don't think we should add more code onto Madara to mitigate a few sites.

how do you know if its just few? since cloudflare issue will get auto closed

**Comment by beer-psi** [comment]
> how do you know if its just few? since cloudflare issue will get auto closed

The point is not how many, the point is trying to fix something that's not broken because Cloudflare is in the way.

**Pull request closed without merging**
