### PR TITLE
Slimeread: Fix apiurl

### LINKED ISSUE #6673: SlimeRead (PT-BR Source) Could not find API URL.
### Source information

SlimeRead 1.4.15

### Source language

Portuguese Brazilian 

### Steps to reproduce

Appears the error Couldn't find API URL.

### Expected behavior

Don't appears the error Couldn't find API URL.

### Actual behavior

Appears the error Couldn't find API URL.

Screenshot_2024-12-18-11-01-05-236_app mihon debug

### Mihon/Tachiyomi version

0.17.1-7033

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #6673 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by MrRobotCoder** [comment]
issue 6673

**Comment by Smol-Ame** [comment]
Put "Closes #6673" in your PR description so it links properly, not in the comments

**Comment by euxande** [comment]
Eu sou novo com essa coisa de programação.  Onde eu coloco esses códigos pra poder executar o slimeread?

**Comment by MrRobotCoder** [comment]
@euxande It's better to wait for the code to be deployed to production.

**Comment by lordenecromante** [comment]
@vetleledaal How to proceed with the PR when there is a region lock?

**Comment by vetleledaal** [comment]
The label is just to note that a VPN is required to review the PR.

**Comment by choppeh** [comment]
@MrRobotCoder I had to make changes in the same place in SlimeRead to include another source. 😔🙏 PR:  #6780

**Comment by lordenecromante** [comment]
No problem @choppeh your change to the apiurl is great... I'll close this PR since yours is more complete and automatically retrieves the URL within the script. Can you just push another commit to the build.gradle changing the overrideVersionCode from 15 to 16?

Since I think choppeh's solution is better implemented, I'm closing this PR.

**Pull request closed without merging**
