### PR TITLE
add Coven Scans

### LINKED ISSUE #2391: add Coven Scan
### Source name

Coven Scan

### Source link

https://cvnscan.com/

### Source language

Portuguese PT-BR

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by kana-shii**
closes #2391
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
remove trailing slash from url

**Comment by kana-shii** [comment]
> remove trailing slash from url

done

**Review by AwkwardPeak7 — DISMISSED** [review]

**Review by AwkwardPeak7 — COMMENTED** [review]
what about the icon?
`https://cvnscan.com/wp-content/uploads/2023/11/cropped-logo2-e1699800058198.png`

**Comment by kana-shii** [comment]
> what about the icon? `https://cvnscan.com/wp-content/uploads/2023/11/cropped-logo2-e1699800058198.png`

just added it

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
