### PR TITLE
ReaperScans: Fix page listing

### LINKED ISSUE #4775: Reaper Scans no pages error but webview works
### Source information

Reaper Scans 1.4.54

### Source language

English

### Steps to reproduce

1. Click new chapter. (Solo Resurrection is what I was trying to read)
2. No pages error pops up
3. Click webview 
4. Webview works fine as if no issue

### Expected behavior

Clicking new chapter loads the chapter.

### Actual behavior

Clicking new chapter gives no pages error.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android  version 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by webmsgr**
Unsure if this should have been a reaper specific patch but...
Fixes #4775

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
no other heancms source have this (yet) so I am more inclined to believe this is reaper specific

**Comment by webmsgr** [comment]
Should I move it to just reaper or keep it as is?

**Comment by AwkwardPeak7** [comment]
move to reaper

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by Zaverxi** [comment]
Not sure about others, but on Reaper's Hard Carry Support the WebView is linking to the novel instead of the webtoon, so the pages are failing despite finding the newest webnovel chapters. Might be a similar issue for others that have both a novel and webtoon with the same name on Reaper.

**Comment by AwkwardPeak7** [comment]
Make a new issue instead of commenting here

**Pull request merged**
