### PR TITLE
Manhwa freak: Update domain

### LINKED ISSUE #3750: Manhwa freak domain changed
### Source information

Manhwa Freak 1.4.36

### Source language

English 

### Source new URL

https://manhwafreak.site

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Yush0DAN**
Closes: #3750

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
seems like they are uploading new chapters on new site while keeping old chapters on the old one... do you know if they will backfill them?

**Comment by Xush00** [comment]
Sorry, I just saw that the new chapters will go to the new domain and the others will stay in the old domain.  What can be done?

**Comment by AwkwardPeak7** [comment]
you can either create a source factory and add both of them in this extension, or you can put extra logic for chapter list to fetch new and old chapters from both domains, like add `#new` to urls for new domain and fetch page list accordingly

**Comment by bapeey** [comment]
New chapters appear in the old domain, but they redirect to the new one. You can check if the response URL is the new domain in `pageListParse` and call the super method if it is (since the new site uses the base MangaThemesia). You will have to add extra logic to save the slug because the chapter URL redirects to the manga page instead of the chapter page

**Pull request closed without merging**
