### PR TITLE
CosmicScans: Fix URL

### LINKED ISSUE #5135: CosmicScans.id: URL changed
### Source information

CosmicScans.id

### Source language

Indonesia

### Source new URL

https://cosmic1.co

### Other details

They've finalized & announced on their Discord that the homepage for CosmicScans.id is cosmictoon.co, but the manga web page is cosmic1.co

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vivalafreak1**
Checklist:
Closes #5135 

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Smol-Ame** [comment]
* No trailing slash in the URL
* Change the URL in the build.gradle too

Follow the checklist as well:
* Bump the versionCode in build.gradle
* Did you actually test your changes? Sometimes it's not as simple as updating the URL
* Reference the relevant issues in your PR description
* Fill out the checklist

**Comment by vivalafreak1** [comment]
> * No trailing slash in the URL
> * Change the URL in the build.gradle too
> 
> Follow the checklist as well:
> 
> * Bump the versionCode in build.gradle
> * Did you actually test your changes? Sometimes it's not as simple as updating the URL
> * Reference the relevant issues in your PR description
> * Fill out the checklist

i accidently click submit, should i make another PR? i already test it and run well

**Comment by Smol-Ame** [comment]
Make the additional changes in the same branch & test if it still works. If it does, push it to your branch and it should show up in your PR

Side-note, it's recommended to create a new branch to do changes/commits instead of your main branch

**Comment by vivalafreak1** [comment]
done.
Thank youu

**Comment by Smol-Ame** [comment]
Reference the related issue (put "Closes #5135" in the PR description), and un-draft the issue so it's a pending PR

**Comment by TheKingTermux** [comment]
> Checklist:
> 
> - [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
> - [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
> - [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
> - [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
> - [x] Have not changed source names
> - [x] Have explicitly kept the `id` if a source's name or language were changed
> - [x] Have tested the modifications by compiling and running the extension through Android Studio
> - [x] Have removed `web_hi_res_512.png` when adding a new extension
> 

Please add "Closes #5135" to this section

Checklist:

Closes #5135

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

They should like this

**Comment by vivalafreak1** [comment]
> > Checklist:
> > 
> > * [ ]  Updated `extVersionCode` value in `build.gradle` for individual extensions
> > * [x]  Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
> > * [ ]  Referenced all related issues in the PR body (e.g. "Closes #xyz")
> > * [ ]  Added the `isNsfw = true` flag in `build.gradle` when appropriate
> > * [x]  Have not changed source names
> > * [x]  Have explicitly kept the `id` if a source's name or language were changed
> > * [x]  Have tested the modifications by compiling and running the extension through Android Studio
> > * [x]  Have removed `web_hi_res_512.png` when adding a new extension
> 
> Please add "Closes #5135" to this section
> 
> Checklist:
> 
> Closes #5135
> 
> * [ ]  Updated `extVersionCode` value in `build.gradle` for individual extensions
> * [x]  Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
> * [ ]  Referenced all related issues in the PR body (e.g. "Closes #xyz")
> * [ ]  Added the `isNsfw = true` flag in `build.gradle` when appropriate
> * [x]  Have not changed source names
> * [x]  Have explicitly kept the `id` if a source's name or language were changed
> * [x]  Have tested the modifications by compiling and running the extension through Android Studio
> * [x]  Have removed `web_hi_res_512.png` when adding a new extension
> 
> They should like this

done,
thx for heads up

**Comment by TheKingTermux** [comment]
> done,
> thx for heads up

I forgot to tell you that you have to check this checklist

- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")

Sorry

**Comment by vivalafreak1** [comment]
> > done,
> > thx for heads up
> 
> I forgot to tell you that you have to check this checklist
> 
> * [x]  Referenced all related issues in the PR body (e.g. "Closes #xyz")
> 
> Sorry

Done, thank you ^^

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
