### PR TITLE
Add CrystalScan and LunarScan to madara

### LINKED ISSUE #455: Crystal Scan
### Source name

crystal scan

### Source link

https://crystalscan.net

### Source language

Português (Brasil)

### Other details

_No response_

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #460: Lunar Scan
### Source name

LunarScan

### Source link

https://lunarscan.com.br/

### Source language

Português 

### Other details

Madara thema 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by domflamingo2**
Closes: #455
Closes: #460

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by beer-psi** [comment]
Make a PR for each source. **And properly test your PRs**. If you can't even do the most basic stuff like *testing the changes you've made* after we've babied you through the last 2 PRs then I'll have to revoke your rights to make pull requests.

For example, are you sure the date format for Crystal Scan is `dd/MM/yyyy`?

The date format is not dd/MM/yyyy.

**Comment by domflamingo2** [comment]
> Make a PR for each source. **And properly test your PRs**. If you can't even do the most basic stuff like _testing the changes you've made_ after we've babied you through the last 2 PRs then I'll have to revoke your rights to make pull requests.
> 
> For example, are you sure the date format for Crystal Scan is `dd/MM/yyyy`?
> 
> The date format is not dd/MM/yyyy.

Testing the PR is kind of difficult, my PC isn't good, I just do it to see if it works because it takes a long time to do it, and the date is on the Brazilian calendar.

The Brazilian calendar is dd/mm/yyyy

image

**Comment by beer-psi** [comment]
> > Make a PR for each source. **And properly test your PRs**. If you can't even do the most basic stuff like _testing the changes you've made_ after we've babied you through the last 2 PRs then I'll have to revoke your rights to make pull requests.
> > For example, are you sure the date format for Crystal Scan is `dd/MM/yyyy`?
> > The date format is not dd/MM/yyyy.
> 
> Testing the PR is kind of difficult, my PC isn't good, I just do it to see if it works because it takes a long time to do it, and the date is on the Brazilian calendar.
> 
> The Brazilian calendar is dd/mm/yyyy

Have you even *tried* parsing the date on the Kotlin playground? https://pl.kotl.in/gkxaLCerT

**Comment by beer-psi** [comment]
On another note, having a terrible PC is also not an excuse for skipping the actual testing. Use your phone if you can't boot an emulator.

You have generally ignored our recommendations to **split up PRs** and **make a separate branch for each PR** repeatedly and we're tired of babying you through pull requests.

**Pull request closed without merging**
