### PR TITLE
Zinmanhwa domain change

### LINKED ISSUE #946: zinmanhwa url change
### Source information

Zinmanhwa 1.4.33

### Source language

English

### Source new URL

https://zinmanga.io

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ghost**
closes #946 
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by yemenihandsome** [comment]
closes #946

**Comment by stevenyomi** [comment]
"Closes #xyz" must be included in your PR description (the first comment, before the checklist): https://github.com/keiyoushi/extensions-source/pull/1006#issue-2117760506 instead of commenting separately. Please edit your PR description to include it.

**Comment by ghost** [comment]
> "Closes #xyz" must be included in your PR description (the first comment, before the checklist): [#1006 (comment)](https://github.com/keiyoushi/extensions-source/pull/1006#issue-2117760506) instead of commenting separately. Please edit your PR description to include it.

OK ,Thank you

**Review by beer-psi — APPROVED** [review]

**Comment by AwkwardPeak7** [comment]
zinmanga.io doesn't use Madara...

**Pull request merged**
