### PR TITLE
Remove Dead Source: BurningScan

### LINKED ISSUE #2005: burning scans
### Source name

burning scans

### Source language

português 

### Source link

https://burningscans.com/

### Other details

The burning scans became Midnight Comics, they will stop posting mangas etc..., I will continue to post the hentai version, they still don't have their Midnight website that's why they will disable the burning to focus on +18

as per their dc
https://discord.gg/QedTxmD5RQ

and their warning

**__CHANGES AND CHANGES__**
Hello Readers! As you may have noticed, we haven't released anything for a few days.
The reason? I'm going to make a change to the scan... I'll bring you news soon. :to sleep:
Today I will make some changes to the channels, and perhaps some will be inactive, but they should return to normal soon."

**__A NEW BEGINNING__**
> Well, let's go then. I'll try to be direct without elaborating too much. For those who don't know, Megumu and I have been working together since 2022, but for personal reasons, he decided to stop. I don't know if this is temporary or forever, but from now on I'll continue alone...

**__MIDNIGHT SCANS????__**
> Well, with Megumu leaving, it's going to be a little more difficult for me to manage everything on my own. So, I decided to create Midnight. And what would she be? Well, that's where I'm posting the hentai works that were from Burning, since it's an easier genre to do and to avoid sitting still for too long. We had already talked about this and had plans to separate the works, with actions at Burning and hentais at Midnight.

**__IS BURNING OVER?__**
> No, Burning is not over and I still intend to continue with it. But, for the moment, I'm going to stop with the action works, because it's a genre that requires a little time and dedication - something I'm not currently having, since I work and haven't had much time available (I think it was enough to notice...). As I said above, hentai is an easier genre that doesn't require a lot of work, so I'm going to "focus" on them until I can organize myself to return to Burning.

**__FUTURE__**
> Burning may be sidelined for a while, but it will not be forgotten. I'm planning, in the future, to only work with works that are posted on Kakao, Naver (although Naver has been giving a lot of copy to works lately... F). And maybe some from Ridi Books. All, I mean **ALL, 100% of the Korean, from the raw to the translation!** So, wait, good things are coming.
- Ah, I even thought about creating a separate server for Midnight, but I decided to leave her on this one since it would be stopped anyway. So, I decided to leave Midnight on this server and, when I announce the return of Burning, I will come back with a new server and a new face.

**__OUR WORKS__**
> We have some beloved works that we used to do that are being done in other scans. So, if you want to continue reading, just go to their websites:

- [Level Up With Skills](https://modescanlator.com/subir-de-nivel-com-habilidades/#google_vignette)
- [The Return Of Apocalypse's Tyrant](https://luratoon.com/manga/o-retorno-do-tirano-do-apocalipse/)

> The rest, you will have to wait until other scans pick them up to do...
- F **Dark Fantasy Paladin** (I loved this work so much).

 **__GOOD...__**
> Well, that's it. I understand anyone who wants to leave the server, etc. But I hope you give it a read to understand things a little.

- **Today I will post chapter 12 of <@&1186042762093678603>**
> I haven't forgotten about the Button combo, but I haven't had much time lately. Soon I should be posting it together with a Please combo. (Maid hasn't had a chapter for a month because the Spanish scan it does simply doesn't post <:bala:1165513579022274611>KKKKKKK)

**_Thank you to everyone who read this far.**"

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by nomaxsnx**
Closes #2005

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
can you clarify, the announcment you posted in that issue seems to imply they will still continue burning scan 🤔

**Comment by nomaxsnx** [comment]
I've spoken to them, they'll soon activate Burning or not, if they don't they'll just change the name, logo and URL of the site.

That's why I'm closing PR.

**Comment by nomaxsnx** [comment]
In case he wants to make mangas, manhua and donghua (but he'll still post them on SlimeRead), until he launches the new site

**Comment by nomaxsnx** [comment]
> can you clarify, the announcment you posted in that issue seems to imply they will still continue burning scan 🤔

I've spoken to them, they'll soon activate Burning or not, if they don't they'll just change the name, logo and URL of the site.

That's why I'm closing PR.

**Comment by nomaxsnx** [comment]
If they announce that they are no longer going to mess with Burgning Scan, I will activate PR again.

**Pull request closed without merging**
