### PR TITLE
Manhwa-Latino: Fix missing chapters

### LINKED ISSUE #5557: Problem in Manhwa-Latino in viewing chapters
### Source information

Manhwa-Latino

### Source language

Espanish

### Steps to reproduce

1- go to any manhwa
2- see that there are missing chapters
3- the only chapters that are shown are the last fifteen

### Expected behavior

that shows all available chapters

### Actual behavior

It only shows the last 15, and lists the rest as "missing" even though they are on the web.

### Mihon/Tachiyomi version

0.16.4.3

### Android version

14

### Other details

Imagen de WhatsApp 2024-10-16 a las 21 21 09_1f682a61

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #5557 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Xush00** [comment]
don't  lose a chapter with pagination?

**Comment by bapeey** [comment]
> don't lose a chapter with pagination?

wdym

**Comment by Xush00** [comment]
When the iteration starts on page 1 and has a new chapter and it doesn't exist yet in the URL without pages, the last one in the list on the first page is lost. Let's say it starts at 55 (new) and ends at 40, the second page starts at 38 and ends at 23. This only happens when a chapter is just uploaded.

**Comment by bapeey** [comment]
that's a site issue

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
