### PR TITLE
Batoto: Merge English and English (US)

### LINKED ISSUE #208: [Bato.to] English (United States) No Search Results
### Source information

Bato.to 1.4.33

### Source language

English (United States) & English

### Steps to reproduce

For source:
* English (US)
  1) Open Popular & latest section for this perticular source
  2) Search any manga title that are actually visible in website but isn't in Tachiyomi .
* English
  1) Search any EN_US content title and English source will include those in it's search result .

### Expected behavior

For source:
* English (US)
  1) Popular & Latest section should work
  2) Search Query should give Results
* English 
  1) Shouldn't contain results that are english (us) manga in search query results.

### Actual behavior

For source:
* English (US)
  Bato.to English (United States) source isn't displaying any search queries or the popular/latest page. 
* English
  Search results contains EN_US contents.

### Tachiyomi version

0.15.2

### Android version

Android 13

### Other details

# Description 
Hey, I've noticed a potential issue with the Batoto extension, particularly in the Bato.to English (United States) source. This specific source isn't displaying any search queries or the popular/latest page. Upon checking the website, I found it only has 5-10 Manga's for the EN_US language (literally in the whole website 😂) .

Upon further investigation, I identified the problem in the website's CSS and the latestUpdateSelector function in BatoTo.kt. The issue stems from the website using the same CSS properties for the "en_us" and "en" languages. I adjusted the function line to resolve the popular and latest page problem:

```kotlin
in setOf("en", "en_us") -> "div#series-list div.col.no-flag"
```

This works great for popular and latest page however, this fix introduced a new problem where the search query for English and English (US) extensions shows the same result, as there's no distinction in the search result page. Unfortunately, the website lacks information on this page to differentiate between English and English (US) Manga's, and requesting a second page for just 5 manga will cause network overhead.

I leave it to the developers to decide whether they want to address this issue or leave it as is. Additionally, I initially mentioned the problem with the English (US) source, but there's also an issue in the BatoTo English source, where this normal English extension includes English (UK) Manga's in its search results. (Same reason as before)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beer-psi**
Closes #208

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by AwkwardPeak7 — COMMENTED** [review]
imo should just remove the en_US version

**Comment by beer-psi** [comment]
> imo should just remove the en_US version

There are a few entries specific to en_US though ¯\\\_(ツ)_/¯ it's not many but it's more than Esperanto, which we also support

**Comment by AwkwardPeak7** [comment]
> There are a few entries specific to en_US though ¯\_(ツ)_/¯ it's not many but it's more than Esperanto, which we also support

wouldn't they appear in the `en` version?

**Comment by beer-psi** [comment]
> > There are a few entries specific to en_US though ¯_(ツ)_/¯ it's not many but it's more than Esperanto, which we also support
> 
> wouldn't they appear in the `en` version?

Only when searching.

**Comment by AwkwardPeak7** [comment]
> Only when searching.

Can merge them.
`siteLang="en_US,en"` for en

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
