### PR TITLE
Remove some of my extensions

### PR DESCRIPTION
**Pull request by ObserverOfTime**
I'd like some of the extensions that I contributed to be removed
from here, since I'll be maintaining them in [my own repo][] instead:

- [x] BakkinReaderX (https://github.com/shadow578/tachiyomi-extensions/commit/1ae23385d822a413d266bb9ae33fe9a38869e446)
  - Bakkin
  - Bakkin Self-hosted
  - UltraLight Scans
- [x] Kouhai Work *(dead)* (https://github.com/shadow578/tachiyomi-extensions/commit/b6fb13ec97728aae79c38e7995c905401290be4e)
- [x] League of Legends (https://github.com/shadow578/tachiyomi-extensions/commit/64ba1e6ba48f38c55d509cbc1e2ae85f7a282774)
- [x] MangAdventure (https://github.com/shadow578/tachiyomi-extensions/commit/f4c4489e6b4d55248afa1dc4681f7c57d1304d7e)
  - Arc-Relight
  - Assorted Scans
- [x] MonochromeCMS (https://github.com/shadow578/tachiyomi-extensions/commit/5c5e997c0493109db9ea0ed2f8404c3d6f71c400)
  - Monochrome Custom
  - Monochrome Scans
- [x] ReaderFront (https://github.com/shadow578/tachiyomi-extensions/commit/d061b6597f230b7f32096e51dd3c82aef7b88884)
  - Ravens Scans
  - Scylla Scans
- [x] vgperson (https://github.com/shadow578/tachiyomi-extensions/commit/2be3e517c4136aa2d40ab368fe44596f686f6c35)

[my own repo]: https://observeroftime.github.io/tachiyomi-extensions/

### CODE REVIEW

**Comment by FourTOne5** [comment]
Denying as I think it'll be beneficial for others to just have one repo with all extensions instead of multiple repos with some extensions (I personally use Scylla and UltraLight).

Also why not just contribute here? By far Keiyoushi is the most shared and well known repo out there.

**Comment by ObserverOfTime** [comment]
> I think it'll be beneficial for others to just have one repo with all extensions

It won't be beneficial to have outdated and/or broken extensions.

> Also why not just contribute here?

Because I don't want to and I no longer have to.

**Comment by FourTOne5** [comment]
> It won't be beneficial to have outdated and/or broken extensions.

I'm not gonna even reply on this.

> Because I don't want to and I no longer have to.

Up to you ¯\\\_(ツ)_/¯

**Comment by ObserverOfTime** [comment]
vgperson is already broken, while Bakkin, MangAdventure, and ReaderFront are outdated. So, you have four options:
1. Remove the extensions (optionally linking to my [and](https://github.com/beerpiss/tachiyomi-unofficial-extensions/tree/repo) [many](https://github.com/stevenyomi/copymanga/tree/repo) [other](https://github.com/npgx/tachiyomi-extensions/tree/repo) [third-party](https://github.com/nzoba/unofficial-tachiyomi-extensions/tree/repo) [repos](https://github.com/Corruptex/tachiyomi-yiffer-extension/tree/repo) on the website).
2. Try to pull any changes I make on my repo (good luck with that).
3. Make similar changes on your own.
4. Let the extensions remain broken or outdated.

**Comment by Sofie99** [comment]
> vgperson is already broken, while Bakkin, MangAdventure, and ReaderFront are outdated. So, you have four options:
> 1. Remove the extensions (optionally linking to my [and](https://github.com/beerpiss/tachiyomi-unofficial-extensions/tree/repo) [many](https://github.com/stevenyomi/copymanga/tree/repo) [other](https://github.com/npgx/tachiyomi-extensions/tree/repo) [third-party](https://github.com/nzoba/unofficial-tachiyomi-extensions/tree/repo) [repos](https://github.com/Corruptex/tachiyomi-yiffer-extension/tree/repo) on the website).
> 2. Try to pull any changes I make on my repo (good luck with that).
> 3. Make similar changes on your own.
> 4. Let the extensions remain broken or outdated.

Why not just maintenance your extension directly in your repository? There's no need to delete it here as well. Many contributors, including myself, will be willing to maintenance it here.

**Comment by ObserverOfTime** [comment]
Users with both repos will have duplicated extensions, but if you want to maintain them anyway, go for it.

**Pull request closed without merging**
