### PR TITLE
Happymh: fix referer for pageListRequest

### LINKED ISSUE #2346: happymh fail to load pages, ald bypass on webview
### Source information

1.4.6

### Source language

chinese

### Steps to reproduce

bypass and read

### Expected behavior

bypass and read

### Actual behavior

bypass and but show blank

### Mihon/Tachiyomi version

0.16.5

### Android version

emui

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by anenasa**
Closes #2346

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by shaunzzzz** [comment]
Nice!
Hopefully this can be reviewed and approved soon.

**Comment by alan0507** [comment]
Thanks for your hard work

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by shaunzzzz** [comment]
Sorry, not sure if it is me, but it is still not working 
Updated to 1.4.11
Refreshed everything, cleared cache, but still having errors

*Edit* it is suddenly working now!
Thanks alot!

**Comment by BabyNurse020517** [comment]
thx it is working

**Comment by salamander7456** [comment]
Thank you for your work! For me, although it's some questions,but the reader works, it's enough ☺️☺️☺️

**Pull request merged**
