### PR TITLE
miaoshang -> miaoqu (unoriginal): update domain

### LINKED ISSUE #2682: miaoshang manhua has changed URL
### Source information

miaoshang manhua 1.4.7

### Source language

Chinese

### Source new URL

https://www.miaoshangmanhua.cc/

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by hsiayuchih**
closes #2682 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
dont change package, just change name and domain in old package

**Comment by hsiayuchih** [comment]
> dont change package, just change name and domain in old package

the main thing is that the domain name and name of the site have changed, so I changed it

**Comment by AwkwardPeak7** [comment]
you changed the package too, it will make the existing one obsolete. That is why i am saying to just change name and domain in old package, instead of moving to new package.

**Comment by hsiayuchih** [comment]
> 您也更改了包，这将使现有的包过时。这就是为什么我说只更改旧包中的名称和域，而不是移动到新包。

I see, can you please help me change it back, it's my first time using this and I'm not familiar with it yet!

**Comment by AwkwardPeak7** [comment]
package here means the directory where code was, you changed that directory too...

**Comment by hsiayuchih** [comment]
> package here means the directory where code was, you changed that directory too...

Does that require me to close the pull request and then resubmit the pull request after the changes are made?

**Comment by Norsze** [comment]
@hsiayuchih look at pull request #4455 , you are only supposed to change the same lines of code in your pull request. 

Currently you have not made an update to the extension you have removed it and made a new extension, all old entries in your library will get disconnected and you would have to migrate them.

**Comment by hsiayuchih** [comment]
> @hsiayuchih look at pull request #4455 , you are only supposed to change the same lines of code in your pull request.
> 
> Currently you have not made an update to the extension you have removed it and made a new extension, all old entries in your library will get disconnected and you would have to migrate them.

ok，thx!

**Comment by hsiayuchih** [comment]
> package here means the directory where code was, you changed that directory too...

Changes have been rolled back

**Comment by AwkwardPeak7** [comment]
you have to keep existing id too. (if old urls are compatible)
old ids can be found here https://github.com/keiyoushi/extensions/blob/repo/index.json

**Comment by hsiayuchih** [comment]
> you have to keep existing id too. (if old urls are compatible) old ids can be found here https://github.com/keiyoushi/extensions/blob/repo/index.json

Okay, if you mean versionId, it's been changed back

**Comment by AwkwardPeak7** [comment]
no version needs to be bumped, simple id in the source class. 
just override it to the current value from the given link
`override val id: Long = <id>`

**Comment by hsiayuchih** [comment]
> no version needs to be bumped, simple id in the source class. just override it to the current value from the given link `override val id: Long = <id>`

But this value is not in the source file

**Comment by AwkwardPeak7** [comment]
changing name requires overriding it, see the pr checklist

**Comment by hsiayuchih** [comment]
> no version needs to be bumped, simple id in the source class. just override it to the current value from the given link `override val id: Long = <id>`

Added, please check again with your help, thanks!

**Pull request closed without merging**
