### PR TITLE
Manhwadesu: Update domain 

### LINKED ISSUE #3938: Manhwadesu
### Source information

https://manhwadesu.one

### Source language

Indonesia 

### Source new URL

https://manhwadesu.cc/

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Yush0DAN**
Closes: #3938

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
rebase on main

**Comment by AwkwardPeak7** [comment]
image
🤔

**Comment by Xush00** [comment]
Open old URL 






which URL?

**Comment by AwkwardPeak7** [comment]
`manhwadesu.guru` shows a alert at top that I screenshot-ed

**Comment by bapeey** [comment]
`manhwadesu.guru` sends to `manhwadesu.cc` (top alert)

Their discord too
image

**Comment by Xush00** [comment]
okey, thanks.  I make the changes

**Comment by Xush00** [comment]
change url but I'm having trouble passing cloudflare

**Comment by Smol-Ame** [comment]
> change url but I'm having trouble passing cloudflare

Maybe try changing the user-agent in your Android Studio's Tachi/Mihon app to see if you can pass CF

**Comment by Xush00** [comment]
changed 5 times and dont work

**Comment by bapeey** [comment]
For some reason I can't bypass cloudflare in app even if Webview works, I also tried changing `popularMangaRequest` to the root page

**Comment by bapeey** [comment]
~Chrome sends the request with POST instead of GET 🤔~ nevermind

**Comment by Xush00** [comment]
Sorry, i tried to fix the cloudflare issue but not works, i will close the pull request so someone else can fix it

**Pull request closed without merging**
