### PR TITLE
Comics Valley: fix latest and popular

### LINKED ISSUE #2575: Comics Valley: Latest & Popular page broken
### Source information

Comics Valley 1.4.36

### Source language

Hindi

### Steps to reproduce

Open Latest & Popular page, no results found

### Expected behavior

Results found

### Actual behavior

No results found

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

Searching still works, I think it needs a /home-3/ after base URL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dngonz**
Closes #2575

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by vetleledaal** [comment]
You could add this to skip a request or two:
```kt
override val useNewChapterEndpoint = true
override val useLoadMoreRequest = LoadMoreStrategy.Always
```

Verify that it actually works, though.

**Comment by dngonz** [comment]
Checked, but unfortunately not, it still does the same requests.

**Comment by vetleledaal** [comment]
> Checked, but unfortunately not, it still does the same requests.

You need to restart the app completely, otherwise it will remember what endpoint to use. If you already did do that there is some flaw in my testing methodology.

**Comment by dngonz** [comment]
Same result maybe I missing something, tried multiple times in different ways but nothing. Apart from the initial requests to get the `.jpg` it always does the same three calls.
Most probably I was doing the tests wrong, could you please tell me how you do it?

**Comment by vetleledaal** [comment]
Not sure about the best way to annotate this, but...:

#### Popular page
1. GET /?s=genre&post_type=wp-manga 403
1. GET /comics-new/?m_orderby=views 200
1. POST /wp-admin/admin-ajax.php (action=madara_load_more&page=1) 200

(1) tries to get the genre and is unrelated to what I mentioned earlier (but should probably still be looked into)
(2) gets page 1, sees that it should use the madara_load_more API instead
(3) is also page 1, but through the madara_load_more API

Here, (2) can be skipped by using `override val useLoadMoreRequest = LoadMoreStrategy.Always`

#### Manga page
1. GET /adult-comics/velamma-latest-hindi-episodes/ 200
1. GET /adult-comics/velamma-latest-hindi-episodes/ 200
1. POST /wp-admin/admin-ajax.php (action=manga_views) 200
1. POST /wp-admin/admin-ajax.php (action=manga_get_chapters) 400
1. GET /adult-comics/velamma-latest-hindi-episodes/ajax/chapters 200

(1) and (2) are for manga details and chapter data. The duplicate request is a limitation of the extension API
(3) is for counting views and can be ignored
(4) tries to get the chapters from the old API since the chapters weren't found in (2)
(5) gets the chapter data from the new API, since it wasn't found in (4)

We can skip (2) and (4) by using `override val useNewChapterEndpoint = true`

#### ---
Madara extensions will save these strategies for subsequent popular/manga requests, so these additional requests will only show up the first time.

Another indication that you should set these explicitly is that it still works as normal. If you're still unsure about some nuances, you would be better off reading the source code of the Madara class.

**Comment by dngonz** [comment]
Got it, now I see the differences. Improvement added.

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
