### PR TITLE
Remove dead sources (at least 1wk)

### PR DESCRIPTION
**Pull request by vetleledaal**
Confirm missing DNS entry (checked now and 1 week ago):
```
vetle@abc ~/d/keiyoushi-extensions (tmp161)> dig elitemanga.org +short A | grep -q . && echo .
                                             dig freewebtooncoins.com +short A | grep -q . && echo .
                                             dig luffymanga.com +short A | grep -q . && echo .
                                             dig mangavisa.com +short A | grep -q . && echo .
                                             dig mangacultivator.com +short A | grep -q . && echo .
                                             dig mangaking.net +short A | grep -q . && echo .
                                             dig mangakitsu.com +short A | grep -q . && echo .
                                             dig mangaqueen.net +short A | grep -q . && echo .
                                             dig mangatoo.com +short A | grep -q . && echo .
                                             dig manhwa18.app +short A | grep -q . && echo .
                                             dig midnightmess.org +short A | grep -q . && echo .
                                             dig opchapters.com +short A | grep -q . && echo .
                                             dig toonmany.com +short A | grep -q . && echo .
                                             dig treemanga.com +short A | grep -q . && echo .
                                             dig webtooncity.com +short A | grep -q . && echo .
                                             dig webtoon.uk +short A | grep -q . && echo .
                                             dig foxwhite.com.br +short A | grep -q . && echo .
                                             dig ladyestelarscan.com.br +short A | grep -q . && echo .
vetle@abc ~/d/keiyoushi-extensions (tmp161) [0|1]> 
```

In other words:
```text
Removed elitemanga.org         via ./src/en/elitemanga
Removed freewebtooncoins.com   via ./src/en/freewebtooncoins
Removed luffymanga.com         via ./src/en/luffymanga
Removed mangavisa.com          via ./src/en/mangaboss
Removed mangacultivator.com    via ./src/en/mangacultivator
Removed mangaking.net          via ./src/en/mangaking
Removed mangakitsu.com         via ./src/en/mangakitsu
Removed mangaqueen.net         via ./src/en/mangaqueen
Removed mangatoo.com           via ./src/en/mangatoo
Removed manhwa18.app           via ./src/en/manhwa18app
Removed midnightmess.org       via ./src/en/midnightmessscans
Removed opchapters.com         via ./src/en/opscans
Removed toonmany.com           via ./src/en/toonmany
Removed treemanga.com          via ./src/en/treemanga
Removed webtooncity.com        via ./src/en/webtooncity
Removed webtoon.uk             via ./src/en/webtoonuk
Removed foxwhite.com.br        via ./src/pt/foxwhite
Removed ladyestelarscan.com.br via ./src/pt/ladyestelarscan
```

Verifying these are gone:
```bash
vetle@abc ~/d/keiyoushi-extensions (tmp161)> rg -F elitemanga.org
                                             rg -F freewebtooncoins.com
                                             rg -F luffymanga.com
                                             rg -F mangavisa.com
                                             rg -F mangacultivator.com
                                             rg -F mangaking.net
                                             rg -F mangakitsu.com
                                             rg -F mangaqueen.net
                                             rg -F mangatoo.com
                                             rg -F manhwa18.app
                                             rg -F midnightmess.org
                                             rg -F opchapters.com
                                             rg -F toonmany.com
                                             rg -F treemanga.com
                                             rg -F webtooncity.com
                                             rg -F webtoon.uk
                                             rg -F foxwhite.com.br
                                             rg -F ladyestelarscan.com.br
vetle@abc ~/d/keiyoushi-extensions (tmp161) [1]> 
```

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by MikeZeDev** [comment]
Mangacultivator changed for https://mangacult.org i think.
Dont know about the others.

**Comment by vetleledaal** [comment]
> Mangacultivator changed for https://mangacult.org/ i think.

Are we seeing the same page? The site looks pretty empty 
image

**Comment by MikeZeDev** [comment]
Sorry remembered adding the new url to Haruneko and i checked right after answering, its now dead.

**Review by AwkwardPeak7 — APPROVED** [review]
MangaKing was (one of) my first pr to tachi extensions 😌

**Pull request merged**
