### PR TITLE
Add ZinChanManga.com

### LINKED ISSUE #2378: URL change request for ZinChanManga
### Source information

ZinChanManga 1.4.36

### Source language

English

### Source new URL

https://zinchanmanga.com/

### Other details

The requested url is more updated rather than the current one. Thank you!

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #2378

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
both sites have different count of manga

**Comment by vetleledaal** [comment]
> both sites have different count of manga

How do you want to handle it? It seems like the current domain is a clone with all the garbled titles.

https://zinchanmanga.net/?s&post_type=wp-manga&m_orderby=latest - garbled
https://zinchanmanga.com/?s&post_type=wp-manga&m_orderby=latest - not garbled

Could just add this as a new site and name it ZinChanManga.com if that is preferable.

**Comment by AwkwardPeak7** [comment]
the original extension, before they used madara was on the .net domain, ([commit](https://github.com/AwkwardPeak7/tachiyomi-extensions/commit/2a7edfd738ccea9fb5fecd8aa3875def919a09a7#diff-23cd841ded6046a65ba1692a78c7796f744c3cbacc94dab4a2088d95d9c33f96L22))
So not really sure which is a clone at this point. Domain can be changed if .com is better; but different count of manga means there may be some titles which don't exist on this one

**Comment by vetleledaal** [comment]
Added the .com site as a separate extension. The .net site was also referred to on the .com site's chapter pages ¯\\\_(ツ)\_/¯

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
