### PR TITLE
Update MangaNoon.kt

### PR DESCRIPTION
**Pull request by ghost**
Update URL

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
See my comment on #908

**Comment by ghost** [comment]
> See my comment on #908

OK

**Comment by ghost** [comment]
> See my comment on #908

Could you please explain to me the merging of two files that you modified, if you would be so kind?

**Comment by SnakeDoc83** [comment]
> > See my comment on #908
> 
> Could you please explain to me the merging of two files that you modified, if you would be so kind?

You can edit both files (as many as needed, really) on a single branch.

**Comment by SnakeDoc83** [comment]
The .com domain seems to be fine and this PR would need work anyway; so rejecting unless it's done properly and with reason.

**Comment by beer-psi** [comment]
Closing obviously untested PR. Please test your changes properly using Android Studio (or AndroidIDE, if you don't have a capable PC) before submitting a pull request.

**Comment by ghost** [comment]
> Closing obviously untested PR. Please test your changes properly using Android Studio (or AndroidIDE, if you don't have a capable PC) before submitting a pull request.

OK I tested it on androidDE

**Comment by beer-psi** [comment]
You still haven't updated the URL in the generator.

**Pull request closed without merging**
