### PR TITLE
Update baseUrl to the new tbcscans domain

### PR DESCRIPTION
**Pull request by JoshieKun**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
where are you getting this new domain from?

you also need to bump the `extVersionCode` in build.gradle, as well as test these changes

**Review by mohamedotaku — COMMENTED** [review]
'https://tcbscans-manga.com' Use madara theme.

**Comment by JoshieKun** [comment]
> where are you getting this new domain from?
> 
> you also need to bump the `extVersionCode` in build.gradle, as well as test these changes

aaah really sorry didn't knew more was required. an for the domain i use this extension a lot to read one piece because i like the translations job they do so right now if you try to use the extension it will give you 502 and if you have the extension install an try to update a manga from there will give you an error. so i verified in my laptop and the old domain is down i look for the new one an is the one i change 

so let me get this right. i have to clone the repo bump the version and run the tests? or do i need to do something else

**Comment by JoshieKun** [comment]
> 'https://tcbscans-manga.com' Use madara theme.

what do you mean by that ?

**Comment by Norsze** [comment]
that is not new, I linked in my PR what the base url was, everything else is a backup. Seriously check the existing URL before you try to fuck over everyone

**Comment by Norsze** [comment]
this is not even TCB, this is a copycat unoriginal one, make a new PR and add it as a new extension

**Pull request closed without merging**
