### PR TITLE
Mark NSFW: Bakaman

### PR DESCRIPTION
**Pull request by cuong-tran**
Since it only mark NSFW so I don't think it worth update version

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [X] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by beer-psi** [comment]
You need to bump the version no matter how small a change it may be.

I'll also have to ask if CoffeeManga and MangaFoxFull really deserves the NSFW flag, since there's very few entries tagged Adult in the first place (~40 out of 2000).

Asking @stevenyomi to weigh in on ManhuaGui.

**Comment by cuong-tran** [comment]
> You need to bump the version no matter how small a change it may be.
> 
> I'll also have to ask if CoffeeManga and MangaFoxFull really deserves the NSFW flag, since there's very few entries tagged Adult in the first place (~40 out of 2000).
> 
> Asking @stevenyomi to weigh in on ManhuaGui.

isn't NSFW flag a keep-out indicator, for kids?

**Comment by beer-psi** [comment]
> isn't NSFW flag a keep-out indicator, for kids?

No? The NSFW flag is both a warning and a sign, depending on the specific person. If every source with even the slightest hint of NSFW was marked as NSFW the tag would become meaningless.

Bakaman is legitimate, there's a sizeable number of NSFW entries on there, I hit a few just browsing the home page, however...
- You can't find NSFW content on CoffeeManga/MangaFoxFull unless you intentionally go out and look for them, say, by filtering with the Adult tag.
- For ManhuaGui, NSFW content may show up in search results, but the extension will refuse to load details and chapters unless you enable the specific extension setting for it.

**Comment by cuong-tran** [comment]
So final decision will be Bakaman only? If yes then I will make the change.

**Review by beer-psi — APPROVED** [review]

**Pull request merged**
