### PR TITLE
RagnarokScanlation: Update domain and fix date format

### LINKED ISSUE #2467: Ragnarok scanlation extension
### Source information

Ragnarok Scanlation 1.4.36

### Source language

Spanish

### Source new URL

https://ragnarokscanlation.org/

### Other details

Due to problems with the previous domain because sr was dropped several times by copyright, it was moved to this domain.
Screenshot_20240417_193759_Discord

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #2467

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
both domains seem to work, but the manga on both have different urls.

One Piece example:
`https://ragnarokscanlation.org/series/one_/`
`https://ragnarokscanlation.net/series/op/`

**Comment by choppeh** [comment]
> both domains seem to work, but the manga on both have different urls.
> 
> One Piece example: `https://ragnarokscanlation.org/series/one_/` `https://ragnarokscanlation.net/series/op/`

What? I checked yesterday, .net was turned off.

**Comment by choppeh** [comment]
> both domains seem to work, but the manga on both have different urls.
> 
> One Piece example: `https://ragnarokscanlation.org/series/one_/` `https://ragnarokscanlation.net/series/op/`

So, I need to update versionId, right?

I understood that the domain change was because of the DMCA

I'll wait a few days to see if .net is disabled again.

**Comment by AwkwardPeak7** [comment]
> I'll wait a few days to see if .net is disabled again.

yes, lets wait

**Pull request closed without merging**
