### PR TITLE
Manwa: Fix page list

### LINKED ISSUE #5060: manwa - No pages found
### Source information

manwa-v1.4.5

### Source language

Chinese

### Steps to reproduce

Read any comic from manwa

### Expected behavior

Enter the reading interface normally and load images correctly.

### Actual behavior

After clicking the "Start" button, it crashes and prompts "No pages found".

### Mihon/Tachiyomi version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) 

### Android version

Android 14

### Other details

But in webview, the manga can be normally read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by anenasa**
Closes #5060
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by yigedajiaque** [comment]
Thanks

**Comment by yigedajiaque** [comment]
I haven’t received an update prompt from tachiyoumi, and even after uninstalling and reinstalling, it’s not the updated version.

我在tachiyomi没收到1.4.6的更新，仍然是1.4.5。我卸载了1.4.5重新安装，仍然是未找到图片

**Comment by Smol-Ame** [comment]
@yigedajiaque this pull request is still open/pending review before it merges into the Keiyoushi repo. The fix hasn't been accepted yet, wait for it to be accepted & you will see an extension update when that happens.

**Comment by yigedajiaque** [comment]
@Smol-Ame Thanks for your answer

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
