### PR TITLE
Update NetTruyen Domain

### PR DESCRIPTION
**Pull request by haruki-takeshi**
Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
this new domain redirects and leads to 404 for me.

also #2886 ?

**Comment by haruki-takeshi** [comment]
> this new domain redirects and leads to 404 for me.
> 
> also #2886 ?

the link in #2886 is fake one.

**Review by haruki-takeshi — COMMENTED** [review]
as information from NetTruyen official fanpage, so domain changed https://www.facebook.com/share/p/WffXT8wa4b22SqSm/?mibextid=oFDknk

**Comment by Karutovn** [comment]
> as information from NetTruyen official fanpage, so domain changed https://www.facebook.com/share/p/WffXT8wa4b22SqSm/?mibextid=oFDknk

So the official fanpage is https://www.facebook.com/nettruyen?mibextid=ZbWKwL not here

**Comment by haruki-takeshi** [comment]
> > as information from NetTruyen official fanpage, so domain changed https://www.facebook.com/share/p/WffXT8wa4b22SqSm/?mibextid=oFDknk
> 
> So the official fanpage is https://www.facebook.com/nettruyen?mibextid=ZbWKwL not here

your provided fanpage didn't update since 2023, I am not sure if it is still working or not

**Comment by vetleledaal** [comment]
`nettruyenvv.com` and `nettruyencc.com` are both copycats.

These are the same:
```
nettruyenbb.com
nettruyenbing.com
nettruyenclub.com
nettruyenee.com
nettruyenff.com
nettruyenhh.com
nettruyenin.com
nettruyenking.com
nettruyenmax.com
nettruyenme.com
nettruyenon.com
nettruyenplus.com
nettruyenss.com
nettruyentt.com
nettruyentv.com
nettruyenup.com
nettruyenus.com
```

There are more domains, but I didn't go back further. The latest domain is `nettruyentt.com`, but it's currently broken. The page @Karutovn linked is also correct.

**Comment by Karutovn** [comment]
> > > as information from NetTruyen official fanpage, so domain changed https://www.facebook.com/share/p/WffXT8wa4b22SqSm/?mibextid=oFDknk
> > 
> > So the official fanpage is https://www.facebook.com/nettruyen?mibextid=ZbWKwL not here
> 
> your provided fanpage didn't update since 2023, I am not sure if it is still working or not

You can check it by send an message on messenger or go to [private group](https://www.facebook.com/share/abJ5koMz1kQQLwSU/?mibextid=A7sQZp) and check it on nettruyen notifications [messenger](https://m.me/j/AbZU7PnMx-redde5/)

**Comment by MikeZeDev** [comment]
Sorry to intrude here, i am interested to know the genuine url so i can use it. I'd rather use an original website than a copycat.
For now i have https://www.nettruyenvv.com and you tell me its no good :D. The one in the PR is a copycat too? Damn.

**Comment by Karutovn** [comment]
For now nettruyen change domain to https://netchuyenvn.com/

**Comment by Karutovn** [comment]
- Something sad nettruyen temporary down and the admin don't have plan for restore for this website

**Pull request closed without merging**
