### PR TITLE
domain change TeamX

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by ghost** [comment]
closes #926

**Comment by beer-psi** [comment]
Look me in the eye and tell me if you've actually tested this. Your commits are made through the GitHub web UI, and you seem like an alt of @yemenihandsome. 

It'd be simple, just screenshot the extension's Popular page.

**Comment by ghost** [comment]
> انظر إلي في عيني وأخبرني إذا كنت قد اختبرت هذا بالفعل. يتم تنفيذ التزاماتك من خلال واجهة مستخدم ويب GitHub، ويبدو أنك بديل@yemenihandsome.
> 
> سيكون الأمر بسيطًا، ما عليك سوى أخذ لقطة شاشة للصفحة الشائعة للامتداد.

IMG-20240204-WA0011
IMG-20240204-WA0010

**Comment by beer-psi** [comment]
Sure then.  Why the alt account though?

**Comment by ghost** [comment]
> Look me in the eye and tell me if you've actually tested this. Your commits are made through the GitHub web UI, and you seem like an alt of @yemenihandsome.
> 
> It'd be simple, just screenshot the extension's Popular page.
  Yes, it is my account @yemenihandsome

**Comment by ghost** [comment]
> Sure then. Why the alt account though?

Because I have two cell phones

**Comment by ghost** [comment]
S10 And LG V60

**Pull request merged**
