### PR TITLE
Add Komga

### LINKED ISSUE #225: Add back Komga
### Source name

Komga

### Source link

https://demo.komga.org/

### Source language

English

### Other details

Add back Komga and the other self hosted sources here now that official extension repo has been archived. 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beer-psi**
Closes #225 

Changes from the official extension:
- Allowed some customization of the chapter name
- Allowed changing the number of additional Komga sources created (max 10). One source will always be created.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by THElegend5** [comment]
Would it be possible to add ability to remap base url? Basically this https://web.archive.org/web/20221102194619/https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13749

**Comment by THElegend5** [comment]
> Would it be possible to add ability to remap base url? Basically this https://web.archive.org/web/20221102194619/https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13749

There was more to this conversation along with some possible ways to do so but they are lost now as far as I can tell.

**Comment by beer-psi** [comment]
> > Would it be possible to add ability to remap base url? Basically this https://web.archive.org/web/20221102194619/https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13749
> 
> There was more to this conversation along with some possible ways to do so but they are lost now as far as I can tell.

I guess the extension can keep its own internal list of previous base URLs? I can't think of anything elegant to work with currently.

**Comment by THElegend5** [comment]
> > > Would it be possible to add ability to remap base url? Basically this https://web.archive.org/web/20221102194619/https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13749
> > 
> > There was more to this conversation along with some possible ways to do so but they are lost now as far as I can tell.
> 
> I guess the extension can keep its own internal list of previous base URLs? I can't think of anything elegant to work with currently.

I think what the proposed solution was to save something like 1/series-url in the app database and the extension replaced the 1 with the base url when searching for stuff and other things,  the number is so as to differentiate between which komga extension you are using as there can be multiple. 
The issue I can think with this might be caused by how this method would work with the komga tracker.

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by beer-psi** [comment]
> I think what the proposed solution was to save something like 1/series-url in the app database and the extension replaced the 1 with the base url when searching for stuff and other things, the number is so as to differentiate between which komga extension you are using as there can be multiple. The issue I can think with this might be caused by how this method would work with the komga tracker.

I think this works as an idea, however implementing it will break two-way tracking built into Mihon/Tachiyomi. I also doubt we have the power to influence any app changes. Feel free to make a feature request for this feature however.

**Comment by jindalpratik** [comment]
> > I think what the proposed solution was to save something like 1/series-url in the app database and the extension replaced the 1 with the base url when searching for stuff and other things, the number is so as to differentiate between which komga extension you are using as there can be multiple. The issue I can think with this might be caused by how this method would work with the komga tracker.
> 
> I think this works as an idea, however implementing it will break two-way tracking built into Mihon/Tachiyomi. I also doubt we have the power to influence any app changes. Feel free to make a feature request for this feature however.

There were already talks to do this in old tachi after a komga refactor that was in works but am unable to find anywhere anymore so it might be possible they do something about it, I'll open a FR for this here.

**Comment by THElegend5** [comment]
> > I think what the proposed solution was to save something like 1/series-url in the app database and the extension replaced the 1 with the base url when searching for stuff and other things, the number is so as to differentiate between which komga extension you are using as there can be multiple. The issue I can think with this might be caused by how this method would work with the komga tracker.
> 
> I think this works as an idea, however implementing it will break two-way tracking built into Mihon/Tachiyomi. I also doubt we have the power to influence any app changes. Feel free to make a feature request for this feature however.

There were already talks to do this in old tachi after a komga refactor that was in works but am unable to find anywhere anymore so it might be possible they do something about it, I'll open a FR for this here.

**Pull request merged**
