### PR TITLE
Remove MangasChan

### LINKED ISSUE #3543: Mangás Chan is Down
### Source name

Mangás Chan

### Source language

Brazilian Portuguese

### Source link

https://mangaschan.net/

### Other details

Web page not available, [error 403](https://foradoar.org/mangaschan.net)

The webpage could not load at the  address because:
net::ERR_NAME_NOT_RESOLVED

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3543

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Riztard** [comment]
can just combine the other removal as 1 pr

**Comment by Riztard** [comment]
Also, if the person opening issue in #3543 is your other account, you dont need to open issue for pr

**Comment by choppeh** [comment]
> Also, if the person opening issue in #3543 is your other account, you dont need to open issue for pr

It's not my account, I just saw some open issues and created a PR

**Comment by choppeh** [comment]
> can just combine the other removal as 1 pr

I'm trying to avoid that. Usually, I do a PR for each issue

Some suggestions in this review: https://github.com/keiyoushi/extensions-source/pull/490#issuecomment-1904636663 (it's not my account either :smile:)

For example, PR #3520 also required additional changes. One PR per issue made it easier to change and review

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
