### PR TITLE
999Hentai: Rebrand to AnimeH

### LINKED ISSUE #4151: 999Hentai: New Domain
### Source information

999Hentai 1.4.6

### Source language

Multi

### Source new URL

https://animeh.to/

### Other details

Current domain & any entry redirects to the new URL

* Supercedes #4150

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #4151 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by Mihover666** [comment]
How to change 999hentai to animeh.to in my tachiyomi?

**Comment by Norsze** [comment]
@Mihover666 you don't do it manually, you just update the extension

**Comment by Mihover666** [comment]
@Norsze I cant update it it didnt show update iconic but it show "obsolete"

**Comment by Norsze** [comment]
@Mihover666 look for the AnimeH extension then and download that, if needed migrate everything from 999 to AnimeH

**Comment by Mihover666** [comment]
@Norsze I cant find it

**Comment by Norsze** [comment]
Go to the Discord for help then @Mihover666 , this comment section is not where you get help

**Comment by Mihover666** [comment]
@Norsze ok thanks for replying to my question

**Pull request merged**
