### PR TITLE
RCO: fix the image couldn't be loaded

### LINKED ISSUE #4115: Readcomiconline.li bug "the image couldn't be loaded"
### Source information

ReadComicOnline 1.4.26

### Source language

English

### Steps to reproduce

1. Choose any comic series
2. Select any issue and open

### Expected behavior

Comic should open and be readable

### Actual behavior

Comic opens in blank and message "The image couldn't be loaded" pops up alongside the options to retry and open in webview

### Mihon/Tachiyomi version

Tachiyomi Stable 15.3

### Android version

Android 11

### Other details

Solving webview captcha doesn't solve the issue.
Chainging user agent string doesn't solve the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by lamaxama**
Close: https://github.com/keiyoushi/extensions-source/issues/4115

Hope they won't break the extension soon.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
remove the hardcoded ua as well, I think they flag that as well, (at least last time I tested)

**Comment by lamaxama** [comment]
@AwkwardPeak7 We cannot remove the hardcoded ua because the extension can only parse the pages for desktop, but we can change to random ua.

**Review by AwkwardPeak7 — APPROVED** [review]
> extension can only parse the pages for desktop

it can be extended in the future for mobile page parsing as well

> Hope they won't break the extension soon.

breaking in 3..2..1..

**Comment by onorino** [comment]
Already broken. Tested now and images are not loaded.
Sad as this source is the only reason for the app to exist outside manga reading.

**Comment by raxod502** [comment]
It works for me, but only for new chapters/series that I have never visited before. I think some bad data is cached in Mihon and needs to be cleared out before sources will work again. I'm not sure yet how to do this without manually editing the database.

Edit: Figured it out from looking through some other issues. You can go to the top-level settings for Mojo, under Data and Storage, there is an option to clear the chapter cache. Do that, go back to any RCO series that was previously broken, it works.

**Comment by onorino** [comment]
> It works for me, but only for new chapters/series that I have never visited before. I think some bad data is cached in Mihon and needs to be cleared out before sources will work again. I'm not sure yet how to do this without manually editing the database.

Already tried with new series and it is still broken form me…

**Comment by AwkwardPeak7** [comment]
clear chapter cache; and come to keiyoushi discord for further help

**Pull request merged**
