### PR TITLE
LuraToon: Add login warning

### PR DESCRIPTION
**Pull request by choppeh**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by bapeey** [comment]
Does the latest tab work? You can simply check the response.request.url in pageListParse, no interceptor required

**Comment by choppeh** [comment]
> Does the latest tab work? You can simply check the response.request.url in pageListParse, no interceptor required

I disabled the latest tab, I think I had seen the old cache

**Comment by bapeey** [comment]
I asked because the interceptor will be thrown in the latest tab with the old implementation, but should still work. Also keep the `pathSegments` empty check in the `pageListParse`

**Comment by choppeh** [comment]
> I asked because the interceptor will be thrown in the latest tab with the old implementation, but should still work. Also keep the `pathSegments` empty check in the `pageListParse`

You're right, I checked PeachScan, and the latestUpdate URL is in the 'root' of the domain

My bad :donkey: :smile:

**Review by AwkwardPeak7 — APPROVED** [review]

**Pull request merged**
